{
 "title": "Cable Modem Stats",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Max Uncorrectables",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawQuery": "SELECT avg(measure_value::bigint)\nFROM $__database.$__table\nWHERE $__timeFilter\n\tAND measure_name = 'uncorrectables' AND measurement='downstream_statistics'"
    }
   ]
  },
  {
   "title": "Current Downstream Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "database": "\"mphuff-personal\"",
     "rawQuery": "WITH uncorrectables AS (\n\tSELECT channel_id, measure_value::bigint AS data, time\n\tFROM $__database.$__table\n\tWHERE time between ago(5m) and now()\n\t\tAND measure_name = 'uncorrectables' AND measurement='downstream_statistics'\n), corrected AS (\n\tSELECT channel_id, measure_value::bigint AS data, time\n\tFROM $__database.$__table\n\tWHERE time between ago(5m) and now()\n\t\tAND measure_name = 'corrected' AND measurement='downstream_statistics'\n), snr AS (\n\tSELECT channel_id, measure_value::double AS data, time\n\tFROM $__database.$__table\n\tWHERE time between ago(5m) and now()\n\t\tAND measure_name = 'snr' AND measurement='downstream_statistics'\n), power AS (\n\tSELECT channel_id, measure_value::double AS data, time\n\tFROM $__database.$__table\n\tWHERE time between ago(5m) and now()\n\t\tAND measure_name = 'power' AND measurement='downstream_statistics'\n), frequency AS (\n\tSELECT channel_id, measure_value::bigint AS data, time\n\tFROM $__database.$__table\n\tWHERE time between ago(5m) and now()\n\t\tAND measure_name = 'frequency' AND measurement='downstream_statistics'\n)\nSELECT a.channel_id, a.data AS uncorrectables, b.data AS corrected, c.data AS snr, d.data AS power, e.data AS frequency\nFROM uncorrectables a\nLEFT OUTER JOIN corrected b ON a.channel_id = b.channel_id\nLEFT OUTER JOIN snr c ON a.channel_id = c.channel_id\nLEFT OUTER JOIN power d ON a.channel_id = d.channel_id \nLEFT OUTER JOIN frequency e ON a.channel_id = e.channel_id \nORDER BY a.time DESC, b.time DESC, c.time DESC, d.time DESC, e.time DESC, CAST(channel_id AS INT) ASC\nLIMIT 16",
     "table": "\"cable_modem_stats\""
    }
   ]
  },
  {
   "title": "Downstream Uncorrectables (Non Negative Derivative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT channel_id, non_negative_derivative_linear(CREATE_TIME_SERIES(time, measure_value::bigint), 5m) AS uncorrectables\nFROM $__database.$__table\nWHERE $__timeFilter\n\tAND measure_name = 'uncorrectables' AND measurement='downstream_statistics'\nGROUP BY channel_id"
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT channel_id, CREATE_TIME_SERIES(time, measure_value::double) AS power\nFROM $__database.$__table\nWHERE $__timeFilter\n\tAND measure_name = 'power' AND measurement='downstream_statistics'\nGROUP BY channel_id"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT channel_id, CREATE_TIME_SERIES(time, measure_value::double) AS power\nFROM $__database.$__table\nWHERE $__timeFilter\n\tAND measure_name = 'snr' AND measurement='downstream_statistics'\nGROUP BY channel_id"
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT channel_id, CREATE_TIME_SERIES(time, measure_value::double) AS power\nFROM $__database.$__table\nWHERE $__timeFilter\n\tAND measure_name = 'power' AND measurement='upstream_statistics'\nGROUP BY channel_id"
    }
   ]
  }
 ]
}