{
 "title": "SB8200",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "downstream_channel",
    "query": "select DISTINCT(\"channel_id\") from (select power, channel_id from downstream_statistics WHERE $timeFilter)"
   },
   {
    "name": "upstream_channel",
    "query": "select DISTINCT(\"channel_id\") from (select power, channel_id from upstream_statistics WHERE $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max Uncorrectables",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"corrected\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval), \"channel_id\" fill(null)",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Downstream Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT last(\"uncorrectables\") AS \"uncorrectables\", last(\"corrected\") AS \"corrected\",  last(\"power\") AS \"power\",  last(\"snr\") AS \"snr\" FROM \"downstream_statistics\"  GROUP BY \"channel_id\" fill(none)",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "uncorrectables" ], "type": "alias" }
      ],
      [
       { "params": [ "corrected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "corrected" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream Uncorrectables (non-negative derivative)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Channel $tag_channel_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channel_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "upstream_statistics",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$upstream_channel$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "content": "<center><h1>Downstream Stats</h1></center>\n\n\n\n\n"
  },
  {
   "title": "Channel  $downstream_channel - Uncorrectables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "repeat": "downstream_channel",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Uncorrectables",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "uncorrectables" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel  $downstream_channel - Corrected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "repeat": "downstream_channel",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Corrected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "corrected" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel  $downstream_channel - Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "repeat": "downstream_channel",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  },
  {
   "title": "Channel  $downstream_channel - SNR/MER",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "repeat": "downstream_channel",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "downstream_statistics",
     "query": "SELECT mean(\"uncorrectables\") FROM \"downstream_statistics\" WHERE (\"channel_id\" =~ /^$downstream_channel$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "channel_id", "operator": "=~", "value": "/^$downstream_channel$/" }
     ]
    }
   ]
  }
 ]
}